name: Build Android APK Manually trigger
on: workflow_dispatch
jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5



      name: Domain layer
        path: domain
        steps:
          - name: Pub clean
            run: flutter clean
          - name: Pub Get
            run: flutter pub get
          - name: Build Runner build
            run: dart run build_runner build --delete-conflicting-outputs

      name: Data layer
        path: domain
        steps:
          - name: Pub clean
            run: flutter clean
          - name: Pub Get
            run: flutter pub get
          - name: Build Runner build
            run: dart run build_runner build --delete-conflicting-outputs

      name: Presentation layer
        path: domain
        steps:
          - name: Pub clean
            run: flutter clean
          - name: Pub Get
            run: flutter pub get


      - name: Build apk
        run: flutter build apk --release

      - name: APK upload
        uses: actions/upload-artifact@v4
        with:
          name:  build-artifacts.apk  # Include PR number in name
          path: build/app/outputs/flutter-apk/app-release.apk